name: Run Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ">=16.8.0"
          check-latest: true
      - name: Install dependencies
        run: npm install 
      - name: "Run Test"
        run: npm test
